networks:
  my_network:
    driver: bridge

services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend/data.db:/app/data.db
    networks:
      - my_network


  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    networks:
      - my_network
